### PR TITLE
Add more icons from eza

### PR DESCRIPTION
**Pull request by Freed-Wu**
Add more icons from eza

Use scripts/generate-json.sh to generate:

- assets/json/extension.json
- assets/json/basename.json

https://github.com/orgs/eza-community/discussions/1270

Perhaps upstrem can provide json files directly.

## Summary by CodeRabbit

- **New Features**
	- Introduced new JSON files for file name and extension mappings, enhancing visual representation with corresponding icons.
	- Added a new shell script to automate JSON file generation from specified sources.
	- New Nix shell configuration file created for easier development environment setup.

- **Bug Fixes**
	- Updated variable handling in Vim scripts to merge additional JSON data sources, improving configuration options.

- **Chores**
	- Added new submodule configuration for better dependency management.

### CODE REVIEW

**Comment by lambdalisue** [comment]
@Freed-Wu 

I think the idea of using eza’s icons is excellent. However, incorporating this approach as it is in the current version poses challenges in terms of compatibility with previous versions. Since this plugin is licensed under MIT, you are free to modify it as long as the license requirements are met. How about forking it into a completely new plugin, such as vim-nerdfont-eza, and hosting it in the eza-community repository?

**Comment by Freed-Wu** [comment]
fork shouldn't be a good choice. It will bring confusion and split the power of contributors.

> incorporating this approach as it is in the current version poses challenges in terms of compatibility with previous versions.

Currently, eza have more icons than this repo. we can utilize it to provide better user experience.
However, some icons of this project are missing in eza, which result in incompatibility with previous versions. IMO:

1. PR to add them to eza.
2. modify the script and merge the json with old data, not create a new json

**Comment by lambdalisue** [comment]
It depends on the purpose of this PR.

If the purpose of this PR is simply to “add icons,” it would be welcomed. In that case, including a mechanism for synchronization wouldn’t be necessary.
However, if the purpose of this PR is to “provide the same icons as eza,” then forking would be a better approach since the core purpose of the plugin would essentially change.

Based on the changes in this PR, which include a synchronization script, I assumed it aligns with the latter purpose and hence suggested forking.

**Comment by Freed-Wu** [comment]
OK, I'll remove the mechanism for synchronization.

**Pull request closed without merging**
