### PR TITLE
Add More Icons (especially around JavaScript ecosystem)

### PR DESCRIPTION
**Pull request by AsPulse**
Subject says it all.

Here is screenshot of diff:
image

### CODE REVIEW

**Review by lambdalisue — CHANGES_REQUESTED** [review]
Thanks. It seems the JSON is not sorted and CI fails so please fix it.

**Comment by AsPulse** [comment]
Sorry, I fixed it in de07736 ! 

I made the shell script that sorts json by keys `assets/json/sort.js` for only me (requires jq) in 7507d9d .
Would you mind if I include the change to this PR?
(If you regard it as inappropriate, feel free to revert the commit!)

**Review by lambdalisue — CHANGES_REQUESTED** [review]
> I made the shell script that sorts json by keys assets/json/sort.js for only me (requires jq) in https://github.com/lambdalisue/nerdfont.vim/commit/7507d9d754d140b2e571d58ca9ca061891c18b36 .
Would you mind if I include the change to this PR?
(If you regard it as inappropriate, feel free to revert the commit!)

Thanks but please remove it.

**Comment by AsPulse** [comment]
> > I made the shell script that sorts json by keys assets/json/sort.js for only me (requires jq) in https://github.com/lambdalisue/nerdfont.vim/commit/7507d9d754d140b2e571d58ca9ca061891c18b36 .
> Would you mind if I include the change to this PR?
> (If you regard it as inappropriate, feel free to revert the commit!)
> 
> Thanks but please remove it.

Ok, I did it.
Thank you too for taking your time…… .ᐟ.ᐟ.ᐟ

**Pull request merged**
